version: '3'
services:

  api:
    build:
      context: ./api
    volumes:
      - ./api:/go/src/github.com/user/Sach97/api
    links:
      - postgres
    networks:
      - api-network
  postgres:
    build : ./postgres
    volumes:
      - ./postgres/pgdata:/pgdata
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
      PGDATA: /pgdata
    ports:
      - 5432:5432

networks:
  api-network: